#!/usr/bin/env python3
"""
GitHub Issue Analysis Agent
Analyzes incoming issues using Copilot CLI to determine completeness and quality.
"""

import os
import subprocess
from pathlib import Path
from github import Github

class IssueAnalysisAgent:
    def __init__(self):
        self.github_token = os.environ['GITHUB_TOKEN']
        self.copilot_pat = os.environ.get('COPILOT_PAT', os.environ['GITHUB_TOKEN'])
        self.issue_number = os.environ['ISSUE_NUMBER']
        self.issue_title = os.environ['ISSUE_TITLE']
        self.issue_body = os.environ.get('ISSUE_BODY', '')
        self.issue_author = os.environ['ISSUE_AUTHOR']
        self.repository = os.environ['REPOSITORY']
        
        self.gh = Github(self.github_token)
        self.repo = self.gh.get_repo(self.repository)
        self.issue = self.repo.get_issue(int(self.issue_number))
        
    def run_copilot_analysis(self):
        """Execute copilot CLI with the IssueAnalysisPrompt.md template."""
        print(f"Analyzing issue #{self.issue_number}: {self.issue_title}")
        
        # Load the prompt template
        prompt_file = Path(".github/IssueAnalysisPrompt.md")
        if not prompt_file.exists():
            print(f"Error: {prompt_file} not found")
            return None
            
        prompt_template = prompt_file.read_text()
        
        # Replace placeholders with actual issue data
        prompt = prompt_template.replace("{ISSUE_TITLE}", self.issue_title)
        prompt = prompt.replace("{ISSUE_BODY}", self.issue_body or "(No description provided)")
        
        # Run copilot CLI
        cmd = ['copilot', '-p', prompt]
        
        env = os.environ.copy()
        env['GITHUB_TOKEN'] = self.copilot_pat
        
        try:
            print("Running Copilot CLI analysis...")
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                env=env,
                timeout=120
            )
            
            if result.returncode == 0:
                print("Analysis completed successfully")
                return result.stdout
            else:
                print(f"Copilot CLI failed with exit code {result.returncode}")
                print(f"STDERR: {result.stderr}")
                return None
                
        except subprocess.TimeoutExpired:
            print("Copilot command timed out after 120 seconds")
            return None
        except Exception as e:
            print(f"Error running copilot: {e}")
            return None
    
    def post_analysis_comment(self, analysis):
        """Post the analysis as a comment on the issue."""
        if not analysis:
            print("No analysis to post")
            return
            
        comment = f"""## 🤖 Issue Analysis

{analysis}

---
*This analysis was automatically generated by GitHub Copilot to help maintainers review this issue.*
"""
        
        try:
            self.issue.create_comment(comment)
            print(f"Posted analysis comment to issue #{self.issue_number}")
        except Exception as e:
            print(f"Failed to post comment: {e}")
            raise
    
    def run(self):
        """Execute the analysis workflow."""
        try:
            # Run the analysis
            analysis = self.run_copilot_analysis()
            
            if not analysis:
                print("Failed to generate analysis")
                return
            
            # Post the analysis as a comment
            self.post_analysis_comment(analysis)
            
            print("Analysis workflow completed successfully")
            
        except Exception as e:
            print(f"Error during analysis workflow: {e}")
            raise


if __name__ == "__main__":
    agent = IssueAnalysisAgent()
    agent.run()
